import { useEffect, useState } from 'react';
import { Cloud, CloudUpload, LogIn, LogOut, UserPlus } from 'lucide-react';
import { cloudConfigured, cloudSession, cloudSignIn, cloudSignOut, cloudSignUp, syncCloudJournal } from '../services/cloud';

export function CloudAccount() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [signedIn, setSignedIn] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { cloudSession().then(session => setSignedIn(session?.user.email ?? '')); }, []);
  async function run(action: () => Promise<unknown>, success: string) { setLoading(true); setStatus(''); try { await action(); const session = await cloudSession(); setSignedIn(session?.user.email ?? ''); setStatus(success); } catch (error) { setStatus(String(error)); } finally { setLoading(false); } }
  return <section className="clone-page cloud-page"><article className="cloud-card"><Cloud size={28}/><span>ONLINE DATABASE</span><h2>Supabase Cloud Sync</h2><p>Keep trades, playbooks and chart-note screenshots synchronized across Windows, macOS, iOS and Android. GitHub stores source code only.</p>{!cloudConfigured ? <div className="cloud-notice">Configure <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_PUBLISHABLE_KEY</code>, then run the included SQL migration.</div> : signedIn ? <><div className="cloud-user">Signed in as <strong>{signedIn}</strong></div><button className="clone-primary" disabled={loading} onClick={() => run(async () => { const result = await syncCloudJournal(); setStatus(`Synced ${result.uploaded} local and ${result.downloaded} cloud records.`); }, '')}><CloudUpload size={15}/> Sync now</button><button className="cloud-secondary" onClick={() => run(cloudSignOut, 'Signed out.')}><LogOut size={14}/> Sign out</button></> : <><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password"/></label><div className="cloud-actions"><button className="clone-primary" disabled={loading} onClick={() => run(() => cloudSignIn(email, password), 'Signed in.')}><LogIn size={14}/> Sign in</button><button className="cloud-secondary" disabled={loading} onClick={() => run(() => cloudSignUp(email, password), 'Account created. Check your email if confirmation is enabled.')}><UserPlus size={14}/> Create account</button></div></>}{status && <div className="cloud-status">{status}</div>}</article></section>;
}
